[tools]
rust = { version = "1.91.1", components = "clippy,rustfmt" }

[tasks.check]
depends = [
    "check:rustfmt",
]

[tasks."check:rustfmt"]
run = "cargo fmt --check"

[tasks.fix]
depends = [
    "fix:rustfmt"
]

[tasks."fix:rustfmt"]
run = "cargo fmt"
