name: CI - Solvers - C++
on:
  workflow_call:
    inputs:
      homebrew-downloads-hash-from-prepare-macos:
        description: Hash of cached Homebrew downloads on MacOS
        required: true
        type: string
      homebrew-downloads-hash-from-prepare-ubuntu:
        description: Hash of cached Homebrew downloads on Ubuntu
        required: true
        type: string
  workflow_dispatch:
permissions:
  contents: read

jobs:
  # Checks
  build-test-run:
    uses: ./.github/workflows/cpp-build-test-run.yaml
    secrets: inherit
    with:
      homebrew-downloads-hash-from-prepare-macos: ${{ inputs.homebrew-downloads-hash-from-prepare-macos }}
      homebrew-downloads-hash-from-prepare-ubuntu: ${{ inputs.homebrew-downloads-hash-from-prepare-ubuntu }}

  check-clang-format:
    uses: ./.github/workflows/mise-task.yaml
    with:
      directory: solvers/cpp
      task: check:clang-format

  check-gersemi:
    uses: ./.github/workflows/mise-task.yaml
    with:
      directory: solvers/cpp
      task: check:gersemi

  # Check for all green CI for C++
  check:
    if: always()
    needs:
      - build-test-run
      - check-clang-format
      - check-gersemi
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
