name: Homebrew - clean cache
on:
  workflow_call:
    inputs:
      downloads-hash-from-prepare:
        description: Hash of cached Homebrew downloads. If not provided, the latest cached downloads will be used.
        required: false
        type: string
      runner:
        description: Runner to use
        required: true
        type: string
  workflow_dispatch:
    inputs:
      downloads-hash-from-prepare:
        description: Hash of cached Homebrew downloads. If not provided, the latest cached downloads will be used.
        required: false
        type: string
      runner:
        default: ubuntu-24.04
        description: Runner to use
        required: true
        type: string
permissions:
  contents: read

jobs:
  clean-cache:
    name: Clean Homebrew cache
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Clean cache
        uses: ./.github/actions/homebrew-packages-setup
        with:
          cache-mode: clean
          downloads-hash-from-prepare: ${{ inputs.downloads-hash-from-prepare }}
