name: Homebrew - prepare cache
on:
  workflow_call:
    inputs:
      runner:
        description: Runner to use
        required: true
        type: string
    outputs:
      downloads-hash:
        description: Hash of cached downloads.
        value: ${{ jobs.prepare-cache.outputs.downloads-hash }}
  workflow_dispatch:
    inputs:
      runner:
        default: ubuntu-24.04
        description: Runner to use
        required: true
        type: string
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Homebrew cache
    outputs:
      downloads-hash: ${{ steps.prepare-cache.outputs.downloads-hash }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - id: prepare-cache
        name: Prepare cache
        uses: ./.github/actions/homebrew-packages-setup
        with:
          cache-mode: prepare
