name: Mise task
on:
  workflow_call:
    inputs:
      directory:
        description: Directory to run mise task in
        required: true
        type: string
      runner:
        default: ubuntu-24.04
        description: Runner to use
        required: false
        type: string
      task:
        description: Task to run
        required: true
        type: string
  workflow_dispatch:
    inputs:
      directory:
        description: Directory to run mise task in
        options:
          - .
          - aoc-main
          - solvers/cpp
          - solvers/python
          - solvers/rust
        required: true
        type: choice
      runner:
        default: ubuntu-24.04
        description: Runner to use
        required: true
        type: string
      task:
        description: Task to run
        required: true
        type: string
permissions:
  contents: read

jobs:
  task:
    name: Mise task - ${{ inputs.task }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Restore tools
        uses: ./.github/actions/mise-project-setup
        with:
          directory: ${{ inputs.directory }}

      - name: Run task - ${{ inputs.task }}

        env:
          MISE_TASK: ${{ inputs.task }}
        run: mise run "${MISE_TASK}"
        shell: bash
        working-directory: ${{ inputs.directory }}
