name: Mise + uv - prepare cache
on:
  workflow_call:
    inputs:
      directory:
        description: Directory containing uv project
        required: true
        type: string
      runner:
        description: Runner to use
        required: true
        type: string
  workflow_dispatch:
    inputs:
      directory:
        description: Directory containing uv project
        options:
          - aoc-main
          - solvers/python
        required: true
        type: choice
      runner:
        default: ubuntu-24.04
        description: Runner to use
        required: true
        type: string
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare uv cache
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check if cache matches
        id: prepare-cache-check
        uses: ./.github/actions/uv-project-setup
        with:
          cache-mode: prepare-check-match
          directory: ${{ inputs.directory }}

      - if: ${{ steps.prepare-cache-check.outputs.match == 'true' }}
        name: Cache hit found
        run: echo "Cache hit found. No need to prepare or check cache contents."

      - if: ${{ steps.prepare-cache-check.outputs.match != 'true' }}
        name: Restore mise project
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: use
          directory: ${{ inputs.directory }}

      - if: ${{ steps.prepare-cache-check.outputs.match != 'true' }}
        name: Prepare cache
        uses: ./.github/actions/uv-project-setup
        with:
          cache-mode: prepare
          directory: ${{ inputs.directory }}
