name: Mise - prepare cache
on:
  workflow_call:
    inputs:
      runner:
        description: Runner to use
        required: true
        type: string
  workflow_dispatch:
    inputs:
      runner:
        default: ubuntu-24.04
        description: Runner to use
        required: true
        type: string
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Prepare cache
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: prepare
          directory: ""
