name: Python run
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  run:
    name: Run
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Restore mise project
        uses: ./.github/actions/mise-project-setup
        with:
          directory: solvers/python

      - name: Restore uv project
        uses: ./.github/actions/uv-project-setup
        with:
          directory: solvers/python

      - name: Run aoc
        run: mise run aoc:all -- --solver python
